### ISSUE TITLE
Social Media Icons wrap at quite a wide screen

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#23] opened 2016-01-04 23:13 UTC
![53](https://cloud.githubusercontent.com/assets/687780/12103245/9031a3fa-b3a5-11e5-8d52-71ce22a56ff0.png)

Is this a feature or a bug?  The social networking icons seem to wrap at a very wide screen.

-Derek

**Comment by gjb2048** [comment] 2016-01-04 23:16
All bugs are features, just unexpected ones.

**Comment by roelmann** [comment] 2016-01-05 08:41
Its not really a feature or a bug - its a design decision based on the requirements for the sites the theme was originally created for.
The headerlogo area has a class of col-md-8 (header.php L72) and the social icons have a class of col-md-4 (social.php L57).
They could potentially be changed to use flexbox as other areas of the main layout do, but that would be an enhancement for a future version and not a bug fix for this version.
It's not something I would plan on changing in my released version, but it would be fairly easy to change to col-md-7 and col-md-5 respectively if that suits your own site better.

**Comment by roelmann** [comment] 2016-01-05 08:44
POTENTIAL ENHANCEMENT
Adapt div.headerlogo and div.socialicons to use flex layout rather than col-md BS grids

**Comment by roelmann** [comment] 2016-01-20 16:50
Closed as wontfix

**Closed as completed by roelmann** 2016-01-20 16:50 UTC
Labels: wontfix
